### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by aledbf** [planettelex/splunk-crowd-auth#1]
What are the steps to install this (splunk doesn't provide the modules, easy_install, etc.) to add exrternal modules.
(sorry for the question, but I don't use python)

thanks

**Comment by everettj** [comment]
This project just provides a script (crowd-scripted.py). It's an implementation for Crowd as described in http://docs.splunk.com/Documentation/Splunk/latest/Security/Createtheauthenticationscript

So basically, looking at the README, you need:
1. python-crowd to be available on your server
2. Edit crowd-scripted.py so you have the right authentication information for your environment (app_url, app_user, app_pass, maybe splunk_user_group)
3. Put crowd-scripted.py someplace on your server where Splunk can read it.
4. Edit your Splunk authentication.conf as described in: http://docs.splunk.com/Documentation/Splunk/latest/Security/Editauthenticationconf

**Comment by pdjhh** [comment]
Hi guys. Realise this is an old one but I can't undersatdn what splunk_user_group is exactly? can anyone advise?
